import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { theme } from "./components/colors";
import Navbar from "./components/Navbar";
import Footer from "./components/homes/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const isScroll = useScroll();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ color: theme }}
      >
        <Navbar />
        <div className="mt-12">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
